### ISSUE TITLE
How efficient will it be to {buffer: 3600000} (one hour)?

### ISSUE THREAD

**Issue by kadishmal** [jslatts/stalker#11]
### Goal

Send an email notification once in one hour including all files names and time they were changed. If no file changes, no notification.
### Question

I want to buffer file changes every one hour (3,600,000 milliseconds). I haven't tested stalker, so I am asking will it be efficient to do this, or is it not recommended to have large **buffer** value? If not, what is the better solution?

**Comment by jslatts** [comment]
There really should not be a problem using large timeout values, but you will want to test this. Another option is to use stalker to collect the file changes and manage the interval emailing sending yourself. You probably want to somehow persist stalker notifications in case your node process crashes.
