### ISSUE TITLE
When using buffer, files that are found after the buffer are not getting ran against the callback on a separate timeout period.

### ISSUE THREAD

**Issue by jfrux** [jslatts/stalker#13]
Let's say...
I have a buffer set at 5000, and it takes longer than 5 seconds for me to get my files in there so 2 of the files didn't get ran in this 5000 batch.

The last 2 files do not get added to a second 5000 batch, but get ignored all together... as far as I can tell...

Am I doing something wrong or should this be considered a bug?

I'm also running on Windows 2008 Server so I'm wondering if maybe that could be contributing?

**Comment by jslatts** [comment]
It certainly sounds like a bug. The timer should start immediately after a file is dropped and wait 5 seconds. 

It could quite easily be related to windows version of fs.watch(), but I'll try and reproduce it tomorrow on a linux box to make sure there isn't a logic problem.

**Comment by jfrux** [comment]
Any clue on this ?

**Comment by jslatts** [comment]
I have tried to reproduce this on OSX and Linux and have not been able to replicate the issue. It could be related to the windows implementation of watch(), but if you are able to isolate a bug in my code, I will certainly accept a patch.

**Comment by jslatts** [comment]
Closing stale bug.
