### ISSUE TITLE
Stalker shows whole directory files where it is running

### ISSUE THREAD

**Issue by yalamber** [jslatts/stalker#14]
Hello, 
I have following code for stalker test

``` nodejs
stalker.watch('/Users/xyz/Sites/nodetest/stalkerdrop', function(err, file){
    console.log('new file %s', file);
});
```

It should actually show files in folder stalkerdrop right but it shows all files list in nodetest folder instead. the script file is in nodetest folder itself should i move it to stalkerdrop folder?

**Comment by yalamber** [comment]
donot know why but it is working now

**Comment by jslatts** [comment]
It should show you new files in the directory you pass in, yes. Not sure why you would have been getting strange behavior, but if you can reproduce the bug in the future, definitely let me know!
