### ISSUE TITLE
stalker.watch() detecting an unchanged file twice?

### ISSUE THREAD

**Issue by dougtoppin** [jslatts/stalker#16]
I'm on OSX 10.8.5 running node v0.10.2 and stalker 0.0.20. I was wondering if once stalker.watch() has detected a file is there any chance that it might 'see' it again even if nothing about the file changes at all (size, mod date, ...)? In situations where I have a script processing a directory containing more than a 100 files I'm getting a callback from it with the same file name twice (and not expecting it).  Another possibility is that if my code is deleting the file after processing it is it possible that watch() is detecting the deletion and returning the name even if I have not included the deletion callback as an argument?

**Comment by jslatts** [comment]
It definitely should not do that. Can you create a sample case that does it so I can try and reproduce? Does the issue recur every single time or is it random?

**Comment by jslatts** [comment]
Closing stale bug.
