### ISSUE TITLE
Tracking file changes?

### ISSUE THREAD

**Issue by elisee** [jslatts/stalker#2]
Hi!

I'm working on integrating stalker with [socketstream](http://github.com/socketstream/socketstream) debug mode as part of [this issue](https://github.com/socketstream/socketstream/issues/15). Socketstream needs to know when to recompile asset files on-the-fly (it should do so on new / removed / changed files).

The test in checkFile (watcher.js):

> return fn && fn(null, watched[dir].files[base] === stats.mtime.valueOf());

checks whether the (potentially new) file's mtime matches the saved one and if it doesn't, it returns false. This means it returns false whenever the stored value was undefined or less than the file's current mtime.

1) Basically, this means the fnAdd callback will be called for file changes too, not only new files, am I right?
2) If I indeed get this right, would you be interested in a patch that adds a third callback fnChanged, so as to avoid reporting changed files as new? I have it mostly written so just tell me and I'll send a pull request.

**Comment by jslatts** [comment]
The original use case of stalker did not require that file modifications call back. This was accomplished by only watching directories, where a change in mtime means that it is likely a file was removed or deleted. So while watcher.Checkfile does return false if the mtime is different, the fs.watchFile call is never made for anything but directories. 

It will be a bit tricky to add the functionality you are after, but it is certainly possible. You will need to call fs.watchFile for each file in a directory and then fire the fnChanged or fnAdd callback when appropriate (file change vs. directory change via file addition).

I am more than happy to accept the change if you can make it optional and keep the original behavior (just tracking the directories for file add/remove) intact as well.

**Comment by zanona** [comment]
One thing I've noticed is that once you update a file it won't trigger the listener as @jslatts  mentioned. 
But then,  if you add or remove any other file, that **update** will appear on the next callback, for example:

**initial state**:
- index.html
- logo.png

---

updating `index.html` 
**stalker**: (no callback triggered)

---

removing `logo.png`
**stalker**: (`index.html` added, `logo.png` removed)

---

in cases like these It becomes a bit difficult to track what is happening (if it's an update or a new file)

> Please note that the **update** process in question is _non-atomic_, so the listeners for adding files shouldn't be triggered.

**Comment by jslatts** [comment]
Ludicco,

I was able to reproduce this. It is certainly a bug. I am working on writing a test case for it and I will try and git a fix out shortly.
