### ISSUE TITLE
Tests don't pass

### ISSUE THREAD

**Issue by elisee** [jslatts/stalker#3]
The stalker tests don't seem to pass. Here's what I get when I run them from a clean clone (with node v0.4.8 & vows 0.5.8 on Ubuntu 11.04 x86_64).

```
elisee@galaxy:~/Repositories/git/stalker$ vows spec/* --spec

♢ stalker

  calling watch with invalid parameters
    ✓ throws exception when no options or function is passed
    ✓ throw exception when options without function is passed
  calling watch on non-existant path in instant mode
    ✓ calls back with error when path not found
  calling watch on non-existant path in buffer mode
    ✓ calls back with error when path not found
watched file: undefined
  file dropping in watched dir calling stalker.watch
    ✓ fires first callback
```

Notice the "watched file: undefined". Also, the testsuite doesn't end, it just seems to wait forever for something to happen. I'll try to dig into it later but maybe you see anything obvious I missed...

EDIT: I tried it on another machine with the same software installed and I get the same never-ending loop but no "watched file: undefined" message.

Is there anything manual I should do like dropping a file to make the tests pass?

**Comment by jslatts** [comment]
No, the tests are supposed to create their own files. To be honest, I have had some issues with getting them to run reliably, but since I switched over to vows.js, they haven't been failing on my machine. I wonder if it is a matter of differences between OSX and Linux for libeio. Need to think some more about this.

**Comment by jslatts** [comment]
I just made a bunch of fixes to some of the more poorly written tests, they are all passing reliably for me. If you are still having issues, please open another one back up!
