### ISSUE TITLE
Clean shutdown / cancelation

### ISSUE THREAD

**Issue by pquerna** [jslatts/stalker#5]
Currently there isn't any way to cancel a watch for a path.

Perhaps it would be nice if watch() returned an object with a cancel method.

**Comment by jslatts** [comment]
Yeah, this should probably happen. I'll add it in.

**Comment by jslatts** [comment]
Implemented in SHA: 721bdb5a33a72bb4d8880454d82e591648b587c9. Tested by hand. Should write unit tests.

**Comment by jslatts** [comment]
I lied. Most of the implementation is in sha: 7ce0bc3cb42340b41fb6b9802e8713bbd1962087
