### ISSUE TITLE
File created vs Moved

### ISSUE THREAD

**Issue by evilpacket** [jslatts/stalker#6]
If I cat stuff into a new file in a stalked directory stalker sees the new file and tells me about it. 

If I move a file into a stalked directory it does not see the new file, should it?

This was tested very recently with node 0.6.6

**Comment by jslatts** [comment]
It should detect it. When I use the test.js example that is included, I can make it notify me when I copy a file over (like the TODO list). Are you running this on Linux or OSX?

J

**Comment by evilpacket** [comment]
Ubuntu  11.10

Just tried test.js and it failed for me.
1. Ran test.js
2. In another terminal copied TODO into example
3. no detection.

**Comment by evilpacket** [comment]
I lied.

node --version
v0.4.12

**Comment by jslatts** [comment]
I'll have to try and repro this tomorrow on one of my Linux boxes at work. Wonder if fs behaves differently on Linux. 

-Justin

On Jan 2, 2012, at 11:59 AM, Adam Baldwinreply@reply.github.com wrote:

Ubuntu  11.10

Just tried test.js and it failed for me.
1. Ran test.js
2. In another terminal copied TODO into example
3. no detection.

---

**Comment by jslatts** [comment]
So, I don't have v0.4.12 lying around, but I confirmed that it works correctly on ubuntu 11.10 with node v0.6.1:

[code]
On start:
user@ubuntu:~/temp/stalker$ node example/test.js 
I see /home/user/temp/stalker/example/test.js
I see /home/user/temp/stalker/example/inner/teapot

user@ubuntu:~/temp/stalker/example$ echo "blah" > newfile1
I see /home/user/temp/stalker/example/newfile1

user@ubuntu:~/temp/stalker$ cp LICENSE example/
I see /home/user/temp/stalker/example/LICENSE
[/code]

I know that v0.6.X brought a ton of changes (libuv) to the underlying system calls, so it could be that fs was not working correctly in v0.4.12. If you can figure out how to get it working, I'll take a patch, but I'm concerned that the fs.watchFile() call back is simply not firing. 

Can you confirm that it is or is not? If it is firing, then stalker may just be incorrectly interpreting the file mtime.
